- name: install containerd if missing
  ansible.builtin.dnf:
    name: containerd
    state: latest

- name: Reload service containerd, in all cases
  ansible.builtin.service:
    name: containerd
    state: stopped
    
- name: update SystemdCgroup in config.toml and docker deamon.json
  shell: |
    containerd config default > /etc/containerd/config.toml
    sed -e 's/SystemdCgroup = false/SystemdCgroup = true/g' -i /etc/containerd/config.toml
  become: yes

- name: restart services
  shell: |
    systemctl start containerd
  become: yes