---
# tasks file for centos9_install_working_prereqs

- block:
    #- include_tasks: set_host.yml

    - include_tasks: add_repos.yml

    - include_tasks: os_config.yml

    - include_tasks: install_containerd.yml

    - include_tasks: install_kubernetes.yml

    - include_tasks: get_tokens.yml

    - include_tasks: join_cluster.yml

    - include_tasks: update_crictl.yml

  when: worker_state == "join"