- name: disable swap
  shell: |
    swapoff -a

- name: load modules
  shell: |
    modprobe overlay
    modprobe br_netfilter

- name: write kubernetes.conf
  shell: |
    cat << EOF | tee /etc/sysctl.d/kubernetes.conf
    net.bridge.bridge-nf-call-ip6tables = 1
    net.bridge.bridge-nf-call-iptables = 1
    net.ipv4.ip_forward = 1
    EOF

- name: Ensure the changes are used by the current kernel
  shell: |
     sysctl --system