
- shell: |
    dnf install -y kubelet kubeadm kubectl --disableexcludes=kubernetes
  register: install_result
  become: yes

- name: start and enable kubelet service
  ansible.builtin.service:
    name: kubelet
    enabled: yes
    state: started
