- name: install docker
  shell: |
    yum update -y
    yum search docker
    yum info docker
    yum install docker -y

    systemctl start docker
    systemctl enable docker

- name: install containerd.io
  shell: |
    echo '{
      "exec-opts": ["native.cgroupdriver=systemd"]
    }' > /etc/docker/daemon.json
    
    containerd config default | tee /etc/containerd/config.toml
    systemctl restart docker
  become: yes