
- name: install kubernetes
  shell: |
    yum install -y cri-tools
    yum install -y kubelet kubeadm kubectl --disableexcludes=kubernetes --skip-broken
  register: install_result
  become: yes

- name: start and enable kubelet service
  ansible.builtin.service:
    name: kubelet
    enabled: yes
    state: started
