---
# tasks file for centos9_install_working_prereqs

- block:
    #- include_tasks: set_host.yml

    - include_tasks: os_config.yml

    - include_tasks: install_containerd.yml

    - include_tasks: install_kubernetes.yml

    - include_tasks: create_cluster.yml

    - include_tasks: install_cacert.yml

    - include_tasks: install_cni_calico.yml

    - name: allow controller to host pods
      shell: |
        kubectl taint nodes --all  node-role.kubernetes.io/control-plane-
      become: yes

    - name: view node status
      shell: |
        export KUBECONFIG=/etc/kubernetes/admin.conf
        kubectl describe node
      become: yes
      register: node_result

    - name: kubctl describe node
      debug:
        msg: "{{ node_result.stdout }}"

  when: cluster_state == "create"

- include_tasks: reset_cluster.yml
  when: cluster_state == "reset"

- include_tasks: get_status.yml



