- name: remove kubelet service
  shell: |
    yum remove kubelet -y
    yum remove containerd -y
  become: yes

- name: reset cluser
  shell: |
    export KUBECONFIG=/etc/kubernetes/admin.conf
    kubeadm reset --force
  become: yes
  register: reset_result

- debug:
    msg: "{{ reset_result }}"