---
# defaults file for centos9_install_working_prereqs
worker_hostname: "10.212.137.169"
controller_hostname: "10.212.137.105"

kubernetesVersion: stable
kubernetes_apiport: 6443
cacert_format: sha256

kubernetesVersion: stable
calico_manifest: https://raw.githubusercontent.com/projectcalico/calico/v3.27.3/manifests/tigera-operator.yaml
kubernetes_apiport: 6443

critools_rpmrurl: https://download.opensuse.org/repositories/isv:/kubernetes:/core:/stable:/v1.30/rpm/x86_64/cri-tools-1.30.0-150500.1.1.x86_64.rpm